// SPDX-FileCopyrightText: 2026 Agentic Threat Investigator contributors
// SPDX-License-Identifier: AGPL-3.0-only
// Investigation API boundary functions (PR 24B).
//
// All Investigation traffic funnels through the PR 24A centralized client.
// The list request is bounded; cursors are opaque strings passed through
// unchanged and never decoded. Creation sends the caller-supplied
// Idempotency-Key through the CSRF-aware transport.

import { apiGet, apiRequest } from "../api/client";
import type {
  Assessment,
  CreateInvestigationInput,
  CreateInvestigationResult,
  Investigation,
  InvestigationPage,
  InvestigationStatusName,
  Report,
} from "../api/schema-types";

/** Bounded browser list page size (backend maximum is higher). */
export const INVESTIGATION_LIST_PAGE_SIZE = 25;

/** The stable HTTP header carrying the logical submission key (PR 23C). */
export const IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";

/** Bounded list filters; the cursor is opaque and never decoded. */
export interface InvestigationListParams {
  status: InvestigationStatusName | undefined;
  cursor: string | undefined;
}

/** Load one bounded page of Investigations through the keyset contract. */
export async function fetchInvestigationsPage(
  params: InvestigationListParams,
  signal?: AbortSignal,
): Promise<InvestigationPage> {
  const query = new URLSearchParams();
  query.set("limit", String(INVESTIGATION_LIST_PAGE_SIZE));
  if (params.status !== undefined) {
    query.set("status", params.status);
  }
  if (params.cursor !== undefined && params.cursor !== "") {
    query.set("cursor", params.cursor);
  }
  return apiGet<InvestigationPage>(`/investigations?${query.toString()}`, signal);
}

/**
 * Submit one logical Investigation creation attempt with its key.
 *
 * The key is generated by the idempotency attempt helper and retained by
 * the caller for transport-uncertain retries; it is never stored, logged,
 * or placed in the URL. The backend answers 202 with the durable identity.
 */
export async function createInvestigationCommand(
  input: CreateInvestigationInput,
  idempotencyKey: string,
): Promise<CreateInvestigationResult> {
  return apiRequest<CreateInvestigationResult>("/investigations", {
    method: "POST",
    body: input,
    headers: { [IDEMPOTENCY_KEY_HEADER]: idempotencyKey },
  });
}

/** Load the authoritative public operational state of one Investigation. */
export async function fetchInvestigation(
  investigationId: string,
  signal?: AbortSignal,
): Promise<Investigation> {
  return apiGet<Investigation>(`/investigations/${investigationId}`, signal);
}

/** Load the current Assessment through the durable backend pointer. */
export async function fetchCurrentAssessment(
  investigationId: string,
  signal?: AbortSignal,
): Promise<Assessment> {
  return apiGet<Assessment>(
    `/investigations/${investigationId}/assessments/current`,
    signal,
  );
}

/** Load the current Report through the durable backend pointer. */
export async function fetchCurrentReport(
  investigationId: string,
  signal?: AbortSignal,
): Promise<Report> {
  return apiGet<Report>(
    `/investigations/${investigationId}/reports/current`,
    signal,
  );
}

/** Load the deterministic Markdown rendering of one persisted Report. */
export async function fetchReportMarkdown(
  investigationId: string,
  reportId: string,
  signal?: AbortSignal,
): Promise<string> {
  return apiRequest<string>(
    `/investigations/${investigationId}/reports/${reportId}/markdown`,
    { signal, rawText: true },
  );
}