# SPDX-License-Identifier: AGPL-3.0-only
"""Typed error mapping for custom persistence SQLSTATEs.

Versioned stored functions raise typed conflicts with dedicated SQLSTATEs so
repositories can surface application errors without parsing error text.
"""

SQLSTATE_INVESTIGATION_NOT_FOUND = "U18A1"
SQLSTATE_VERSION_CONFLICT = "U18A2"
SQLSTATE_EVIDENCE_DUPLICATE = "U18A3"
SQLSTATE_INVESTIGATION_DUPLICATE = "U18A4"
SQLSTATE_INVALID_TRANSITION = "U18A5"
SQLSTATE_RELATIONSHIP_SOFT_DELETED = "U18C1"
SQLSTATE_ENTITY_SOFT_DELETED = "U18C2"
SQLSTATE_RELATIONSHIP_NOT_FOUND = "U18C3"
# PR 20A Assessment write-path states.
SQLSTATE_ASSESSMENT_DUPLICATE_EVIDENCE = "U20A1"
SQLSTATE_ASSESSMENT_DUPLICATE_SUPPORT = "U20A2"
SQLSTATE_ASSESSMENT_EVIDENCE_INVALID = "U20A3"
SQLSTATE_ASSESSMENT_OBSERVATION_INVALID = "U20A4"
SQLSTATE_ASSESSMENT_REFERENCE_INVALID = "U20A5"
SQLSTATE_ASSESSMENT_NOT_FOUND = "U20A6"
SQLSTATE_ASSESSMENT_DUPLICATE = "U20A7"
SQLSTATE_ASSESSMENT_STRUCTURE_INVALID = "U20A8"
SQLSTATE_ASSESSMENT_GRAPH_CONCURRENT = "U20A9"
SQLSTATE_ASSESSMENT_CURRENT_CONFLICT = "U20AB"
SQLSTATE_ASSESSMENT_INVESTIGATION_MISMATCH = "U20AC"
SQLSTATE_ASSESSMENT_HARD_LIMIT = "U20AD"
# PR 20B Investigation LLM-budget write-path states.
SQLSTATE_BUDGET_COUNTERS_INVALID = "U20B1"
SQLSTATE_LLM_BUDGET_EXHAUSTED = "U20B2"
# PR 21 coordinator transition write-path states.
SQLSTATE_COORDINATOR_STATE_INVALID = "U21A1"
SQLSTATE_INVALID_ANALYSIS_DISPOSITION = "U21A2"
SQLSTATE_OPTIMISTIC_VERSION_REQUIRED = "U21A3"


def sqlstate(error: BaseException) -> str | None:
    """Return the SQLSTATE carried by a DBAPI error, if any."""
    orig = getattr(error, "orig", None)
    state = getattr(orig, "sqlstate", None)
    return state if isinstance(state, str) else None
